import Head from 'next/head'

import {FaInstagram} from 'react-icons/fa'
import {FaFacebook} from 'react-icons/fa'
import {FaLinkedin} from 'react-icons/fa'

export default function Home() {
    return (
        <>
        <Head>
            <title>Full Stack App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/images/6.png" />
        </Head>
            <div className="landing">
                <div className="landing-left">
                    <div>
                        <h1>
                            Web Design.<br />
                            Android + iOS.<br />
                            Desktop Apps.<br />
                        </h1>
                        <p>The one stop shop for all your needs.</p>
                        <FaInstagram className="icon" />
                        <FaFacebook className="icon" />
                        <FaLinkedin className="icon" />
                        <br />
                        <button className="primary-button">
                            <p>Contact Us</p>
                        </button>
                    </div>
                </div>

                <div className="landing-right">
                    <img src="/images/1.png" width="75%" />
                </div>
            </div>
        </>
    )
}